---
- name: Install Apache Tomcat8 using ansible
  hosts: webserver
  remote_user: ubuntu
  become: true
  tasks:
    - name: Update the System Packages
      apt:
        upgrade: yes
        update_cache: yes

    - name: Create a Tomcat User
      user:
        name: tomcat

    - name: Create a Tomcat Group
      group:
        name: tomcat

    - name: Install JAVA
      apt:
        name: default-jdk
        state: present


    - name: Create a Tomcat Directory
      file:
        path: /opt/tomcat8
        owner: tomcat
        group: tomcat
        mode: 755
        recurse: yes

    - name: download & unarchive tomcat8
      unarchive:
        src: https://dlcdn.apache.org/tomcat/tomcat-8/v8.5.85/bin/apache-tomcat-8.5.85.tar.gz
        dest: /opt/tomcat8
        remote_src: yes
        extra_opts: [--strip-components=1]

    - name: Change ownership of tomcat directory
      file:
        path: /opt/tomcat8
        owner: tomcat
        group: tomcat
        mode: "u+rwx,g+rx,o=rx"
        recurse: yes
        state: directory

    - name: create tomcat.service file
      file:
        path: /etc/systemd/system/tomcat.service
        state: touch

    - name: create tomcat service
      blockinfile:
        path: /etc/systemd/system/tomcat.service
        block: |
          [Unit]
          Description=Tomcat - instance %i
          After=syslog.target network.target
          [Service]
          Type=forking
          User=tomcat
          Group=tomcat
          Environment="CATALINA_HOME=/opt/tomcat8/"
          ExecStart=/opt/tomcat8/bin/startup.sh
          ExecStop=/opt/tomcat8/bin/shutdown.sh
          [Install]
          WantedBy=multi-user.target

          ---
    - name: "Copy sampleapp to tomcat webapps direcotry"
      copy:
        src: sampleapp.war
        dest: /opt/tomcat8/webapps

    - name: Start and Enable Tomcat 10 on sever
      systemd:
        name: tomcat
        state: started
        daemon_reload: true
